// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minesweeper.DataAccess;

#nullable disable

namespace Minesweeper.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220213162644_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Minesweeper.DataAccess.Entities.GameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<uint>("AreaHeight")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AreaWidth")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Mines")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<long>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameResults", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a397d8e-bb08-4610-b656-48901bbb835b"),
                            AreaHeight = 10u,
                            AreaWidth = 10u,
                            Mines = 0u,
                            Name = "User 1",
                            Time = 1644769604L
                        },
                        new
                        {
                            Id = new Guid("df725458-0c8c-4988-90d0-ef24460bbdf2"),
                            AreaHeight = 20u,
                            AreaWidth = 20u,
                            Mines = 0u,
                            Name = "User 2",
                            Time = 1644769604L
                        },
                        new
                        {
                            Id = new Guid("bac3b92f-a181-4b0a-9ac8-ba5aaf8ce236"),
                            AreaHeight = 50u,
                            AreaWidth = 25u,
                            Mines = 0u,
                            Name = "User 3",
                            Time = 1644769604L
                        },
                        new
                        {
                            Id = new Guid("445c99bb-7088-4243-8c39-d79effae2691"),
                            AreaHeight = 50u,
                            AreaWidth = 50u,
                            Mines = 0u,
                            Name = "User 4",
                            Time = 1644769604L
                        },
                        new
                        {
                            Id = new Guid("b11b82af-1d7a-4082-b8f5-ceb980090546"),
                            AreaHeight = 100u,
                            AreaWidth = 100u,
                            Mines = 0u,
                            Name = "User 5",
                            Time = 1644769604L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
