// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minesweeper.DataAccess;

#nullable disable

namespace Minesweeper.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.2");

            modelBuilder.Entity("Minesweeper.DataAccess.Entities.GameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<uint>("AreaHeight")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AreaWidth")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Mines")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(true)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GameResults", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4fb20731-278c-4873-bed7-b8e26c5cb1f9"),
                            AreaHeight = 10u,
                            AreaWidth = 10u,
                            Mines = 10u,
                            Name = "User 1",
                            Score = 15,
                            Time = 1644958210L
                        },
                        new
                        {
                            Id = new Guid("d2904665-2213-4a9f-bfec-45fe31f7abb5"),
                            AreaHeight = 20u,
                            AreaWidth = 20u,
                            Mines = 10u,
                            Name = "User 2",
                            Score = 12,
                            Time = 1644958210L
                        },
                        new
                        {
                            Id = new Guid("dbc5805f-9157-4bc3-86f8-d645459eaf23"),
                            AreaHeight = 50u,
                            AreaWidth = 25u,
                            Mines = 10u,
                            Name = "User 3",
                            Score = 12,
                            Time = 1644958210L
                        },
                        new
                        {
                            Id = new Guid("c35d2567-a5f6-4230-95d4-0695581e5cc8"),
                            AreaHeight = 50u,
                            AreaWidth = 50u,
                            Mines = 10u,
                            Name = "User 4",
                            Score = 11,
                            Time = 1644958210L
                        },
                        new
                        {
                            Id = new Guid("b1359b33-8aec-4028-bb8e-e8fa8ae8b194"),
                            AreaHeight = 100u,
                            AreaWidth = 100u,
                            Mines = 10u,
                            Name = "User 5",
                            Score = 10,
                            Time = 1644958210L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
